language: php

php:
  - 5.6
  - 7
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

install:
  - composer selfupdate
  - |
    if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then
      composer require 'codeclimate/php-test-reporter:*' 'satooshi/php-coveralls:*'
    else
      composer install
    fi

script:
  - composer travis

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then vendor/bin/test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: hhvm

addons:
  code_climate:
    repo_token: c978865eace33f5d34862bfa0a8df1637ffea6eaf7a0b4536300222112807d40
